[build]
  command = "npm run build"
  publish = "frontend/build"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
